<div class="cms-inside">
   <div class="text-header">
      arabika<br> o wyjątkowym pochodzeniu
      <p>z upraw organicznych</p>
   </div>
   <div class="widget-block">
      <div class="youtube-start" id="96179" style="width: 965px; height: 550px;background: url({{media url=blocks/origins/film-kawy.png}}) no-repeat 0 0;">
         <div class="youtube-wrapper"></div>
      </div>
      <script>
         youTube.init();
         var player = null;

         jQuery(function() {
             jQuery('#96179').on('click', function() {
                 jQuery('#youtube-player').remove();
                 jQuery('#96179').append('<div id="youtube-player"></div>');
                 youTube.callback = youTube.removeYouTubePlayers;
                 player = new YT.Player('youtube-player', {
                     height: '550',
                     width: '965',
                     videoId: '--ZBYXBxNz0',
                     events: {
                         'onReady': youTube.onPlayerReady,
                         'onStateChange': youTube.onPlayerStateChange
                     }
                 });
             })
         });
      </script>
   </div>
   <div class="text-header">poznaj nasze nowe kawy</div>
   <div class="tab-block">
      <div class="tab-block-top"><span class="tab-1 active" data-tab="tab-1"> <span class="tab-nav">&nbsp;</span> <span class="tab-nav-active">&nbsp;</span> </span> <span class="tab-2" data-tab="tab-2"> <span class="tab-nav">&nbsp;</span> <span class="tab-nav-active">&nbsp;</span> </span> <span class="tab-3" data-tab="tab-3"> <span class="tab-nav">&nbsp;</span> <span class="tab-nav-active">&nbsp;</span> </span></div>
      <div class="tab-block-content">
         <div id="tab-1" class="tab-content active">
            <div class="top-part">&nbsp;</div>
            <div class="bottom-part">
               <p class="top">Ta wyjątkowa organiczna Arabika rośnie w rytmie natury regionu Corquin otoczonego bujnym lasem tropikalnym.<br> <span style="padding-top: 17px; display: inline-block;"> To dzięki tym specyficznym warunkom kawa ta charakteryzuje się szczególnymi nutami w aromacie.</span></p>
               <img src="{{media url=blocks/origins/Honduras-mapa1.gif}}" alt="">
               <p class="left">Staranne ręczne zbieranie tylko w pełni dojrzałych owoców nadaje tej kawie okrągły, zbalansowany smak z delikatnymi nutami miodu, gorzkiej czekolady i słodu.</p>
               <a href="https://www.dolce-gusto.pl/flavours/kawy-origins/espresso-honduras"> <span class="btn-box"> <span class="btn-text">ZAMÓW TERAZ</span> </span> </a>
            </div>
         </div>
         <div id="tab-2" class="tab-content">
            <div class="top-part">&nbsp;</div>
            <div class="bottom-part">
               <p class="top">Na stromych zboczach gór Sierra Nevada w Kolumbii, w bardzo zmiennym klimacie, żyją potomkowie plemienia Tayrona.<br> <span style="padding-top: 17px; display: inline-block;"> Na swych ziemiach ojczystych, uważanych za święte, uprawiają wyjątkową organiczną Arabikę zgodnie z tradycją przodków. </span></p>
               <img src="{{media url=blocks/origins/Colombia-mapa1.gif}}" alt="">
               <p class="left">Z ziaren tych stworzone jest nowe Lungo o charakterystycznym aromacie z subtelnymi nutami prażonych migdałów, gałki muszkatołowej i jęczmienia, które z pewnością Cię zachwycą.</p>
               <a href="https://www.dolce-gusto.pl/flavours/kawy-origins/lungo-colombia"> <span class="btn-box"> <span class="btn-text">ZAMÓW TERAZ</span> </span> </a>
            </div>
         </div>
         <div id="tab-3" class="tab-content">
            <div class="top-part">&nbsp;</div>
            <div class="bottom-part">
               <p class="top">W orzeźwiających wiatrach peruwiańskich gór, w prowincji Cajamarca rośnie wyjątkowa Arabika, uprawiana zgodnie z tradycją Minga – południowoamerykańską filozofią wzajemnej pomocy i szacunku.</p>
               <img src="{{media url=blocks/origins/Peru-mapa1.gif}}" alt="">
               <p class="left">Unikalne warunki klimatyczne oraz szczególna opieka plantatorów wpływają na wyjątkową jakość tego Espresso z niezrównanymi aromatami drewna, lukrecji oraz delikatną nutą różowego pieprzu i przyjemną kwaskową nutą pączków czarnej porzeczki. Zachwycisz się nim.</p>
               <a href="/flavours/kawy-origins/espresso-peru"> <span class="btn-box"> <span class="btn-text">ZAMÓW TERAZ</span> </span> </a>
            </div>
         </div>
      </div>
   </div>
   <div class="text-header">Daj się porwać oryginalnym rytmom</div>
   <div class="widget-block">
      <div class="youtube-start" id="11704" style="width: 965px; height: 550px;background: url(https://dolce-gusto.pl/media/wysiwyg/Origins/opakowania.jpg) no-repeat 0 0;">
         <div class="youtube-wrapper"></div>
      </div>
      <script>
         youTube.init();
         var player = null;

         jQuery(function() {
             jQuery('#11704').on('click', function() {
                 jQuery('#youtube-player').remove();
                 jQuery('#11704').append('<div id="youtube-player"></div>');
                 youTube.callback = youTube.removeYouTubePlayers;
                 player = new YT.Player('youtube-player', {
                     height: '550',
                     width: '965',
                     videoId: 'sp0q7EgbCUM',
                     events: {
                         'onReady': youTube.onPlayerReady,
                         'onStateChange': youTube.onPlayerStateChange
                     }
                 });
             })
         });
      </script>
   </div>
   <div class="text-header">zachwyć się oryginalnym smakiem</div>
   <div class="block-3elemnts">
      <div class="element-left">
         <div class="top">Nowe Espresso</div>
         <div class="name">Corquin</div>
         <div class="desc">Gładkie i zbalansowane espresso z nutami miodu, gorzkiej czekolady i słodu.</div>
         <div class="intense">Intensywność: 6</div>
         <a href="https://www.dolce-gusto.pl/flavours/kawy-origins/espresso-honduras"> <span class="btn-box"> <span class="btn-text">ZAMÓW TERAZ</span> </span> </a>
      </div>
      <div class="element-center">
         <div class="top">Nowe Lungo</div>
         <div class="name">Sierra Nevada</div>
         <div class="desc">Delikatne Lungo <br>z nutami prażonych migdałów, gałki muszkatołowej i jęczmienia.</div>
         <div class="intense">Intensywność: 5</div>
         <a href="https://www.dolce-gusto.pl/flavours/kawy-origins/lungo-colombia"> <span class="btn-box"> <span class="btn-text">ZAMÓW TERAZ</span> </span> </a>
      </div>
      <div class="element-right">
         <div class="top">Nowe Espresso</div>
         <div class="name">Cajamarca</div>
         <div class="desc">Intensywne espresso z aromatami drewna, lukrecji oraz z subtelną nutą różowego pieprzu i czarnej porzeczki.</div>
         <div class="intense">Intensywność: 8</div>
         <a href="https://www.dolce-gusto.pl/flavours/kawy-origins/espresso-peru"> <span class="btn-box"> <span class="btn-text">ZAMÓW TERAZ</span> </span> </a>
      </div>
   </div>
   <div class="text-header">
      Arabika
      <p class="text-header-additional">Arabika (Coffea Arabica) to jedna z dwóch, obok Robusty, stosowanych w produkcji kawy odmian krzewu kawowego</p>
   </div>
   <div class="block-arabica">
      <div class="block-arabica-right">Kawowce Arabiki są uprawiane w strefie międzyzwrotnikowej, w tropikalnych terenach wyżynnych. Potrzebują żyznej, często wulkanicznej gleby i sporych opadów.<br> <span style="margin-top: 38px; display: inline-block;">Są one bardziej wymagające w uprawie i wrażliwe na warunki atmosferyczne niż Robusta.</span></div>
      <div class="block-arabica-left" style="
         color: #000;
         ">Kawa z ziaren Arabiki jest delikatna, harmonijna w smaku, z owocowymi lub kwiatowymi nutami oraz charakteryzuje się bogatym aromatem. Ziarna Arabiki zawierają też mniej kofeiny niż ziarna Robusty, dlatego też częściej stosuje się je w komponowaniu kaw przeznaczonych do delektowania się, raczej popołudniowych, idealnych do chwili relaksu, niż do kaw porannych, bardziej pobudzających, gdzie z powodzeniem stosuje się Robustę.</div>
      <div class="text-header">wszystkie kawy 100% Arabika</div>
      <a href="https://www.dolce-gusto.pl/flavours/kawy-arabika"> <span class="btn-box"> <span class="btn-text">odkryj</span> </span> </a>
   </div>
   <script type="text/javascript">// <![CDATA[
      jQuery(document).ready(function () {
                      jQuery('.tab-block-top span').click(function () {
                          var tab_id = jQuery(this).attr('data-tab');
                          jQuery('.tab-block-top span').removeClass('active');
                          jQuery('.tab-content').removeClass('active');
                          jQuery(this).addClass('active');
                          jQuery("#" + tab_id).addClass('active');
                      });
                  });
      ]]>
   </script>
</div>
